### PR TITLE
Remove useless dependency on commons-codec

### PR DESCRIPTION
**Pull request by Maxoid**
Sorry for the little mess with the imports...

### CODE REVIEW

**Comment by tomdesair** [comment]
Hi @Maxoid,

Thank you very much for your pull request. This would indeed be an improvement!

But apparently there was still a Travis configuration issue that made the SonarCloud code style checks fail. I've pushed some changes to the master branch to correct this. 

Could you rebase your branch on these changes and push again? Normally the Travis build should work then.

I'll try to finalise the documentation and push this jar to Maven in the coming week.

**Comment by Maxoid** [comment]
Hi @tomdesair !
Seems, it didn't help.

**Comment by tomdesair** [comment]
Apparently SonarCloud does not support analyzing pull-requests from forks. Therefor I made a few changes in the master branch so that Sonar is not executed on pull-requests from forks. In addition I've configured Coveralls.io to check on the unit test coverage.

Could you please pull these changes into your branch and try again? Thanks!

**Comment by Maxoid** [comment]
Great work @tomdesair !
Why not put it on the list of implementation at [tus.io](https://tus.io/implementations.html) ?
It much better than the official one.

**Comment by tomdesair** [comment]
Once I've uploaded the Jar to Maven, I'll ask the people of tus.io to list this repository on the implementations page. And thanks again for the help!

**Pull request merged**
