### PR TITLE
Upgrade to Spring boot 3

### PR DESCRIPTION
**Pull request by ghoshrahul**
Pull request for this [issue](https://github.com/tomdesair/tus-java-server/issues/48)

* Use jakarta api instead of javax api
* Change the source and target to 1.8
* Fix test cases
* Date format changes. Refer: https://github.com/spring-projects/spring-framework/issues/16531
* Documentation changes
* Version changes

### CODE REVIEW

**Comment by mich9463** [comment]
Since this change would prohibit deployment to any pre Jakarta-Servlet 6.0 servlet container, like Tomcat 9, I'd propose  a larger bump in version (maybe 1.1).

**Comment by ksvraja** [comment]
Hi @ghoshrahul 
I have tried the similar upgrade (for jakarta update), and did not find any need to update the logic in - src/test/java/me/desair/tus/server/creation/ITCreationExtension.java file.   

Could you describe the change required for notnull --> any  check. 

fyi- I also faced the dateformat changes.

**Comment by gagniou** [comment]
hi, 

do you have any idea when will the release take place ? I am waiting  the 1.0.0-3.0 for a project in springboot 3

**Comment by tomdesair** [comment]
This has now been released to Maven Central as version `1.0.0-3.0`: https://repo1.maven.org/maven2/me/desair/tus/tus-java-server/1.0.0-3.0/

**Pull request merged**
